@baseUrl=http://localhost:3002/
@tokenUser="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJ1c2VybmFtZSI6Ik9ra3lCb3kifQ.7tZhRHeXcCXqT0o_zDA5EI3tnta0M-4ltPT9xndsJ_0"


GET {{baseUrl}}?query=movies HTTP/1.1
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJ1c2VybmFtZSI6Ik9ra3lCb3kifQ.7tZhRHeXcCXqT0o_zDA5EI3tnta0M-4ltPT9xndsJ_0"
}

###

GET {{baseUrl}}/?mutation=movies HTTP/1.1
Content-Type: application/json

{
  "accessToken": {{tokenUser}},
  "category": "Pekerjaan",
  "tags" : ["coding","python"],
  "duration" : 20930,
  "total_duration" : 37462
}

###

POST http://localhost:3000/api/v1/user/login HTTP/1.1
Content-Type: "application/json"

{
    "username": "OkkyBoy",
    "password": "admin"
}

###

POST http://localhost:3000/api/v1/user/login HTTP/1.1
Content-Type: "application/json"

{
    "username": "OkkyBoy",
    "password": "admin"
}

###
POST http://localhost:3000/api/v1/user/token HTTP/1.1
Content-Type: "application/json"

{
    "accessToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJ1c2VybmFtZSI6Ik9ra3lCb3kifQ.7tZhRHeXcCXqT0o_zDA5EI3tnta0M-4ltPT9xndsJ_0"
}