version: '3'
services:
  backend:
    container_name: api-gateaway-movie
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3002:3002
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
